name: GCOOS
channels:
  - conda-forge
dependencies:
  - python=3.6
  - cartopy
  - datashader
  - erddapy
  - geoviews
  - hvplot
  - jupyter
  - jupyter_contrib_nbextensions
  - matplotlib
  - nb_conda_kernels
  - netCDF4
  - numpy
  - pandas
  - requests
  - xarray
