name: GCOOS
channels:
  - defaults
dependencies:
  - python=3.6
  - pip
  - cartopy
  - datashader
  - geoviews
  - hvplot
  - jupyter
  - jupyter_contrib_nbextensions
  - matplotlib
  - nb_conda_kernels
  - netCDF4
  - numpy
  - pandas
  - requests
  - xarray
  - pip:
    - erddapy
